primer commit models/contactos
DJPORTILLO30/CRM-UMG pull request #13
Opened 2022-09-20 04:59 UTC by larochem20

creacion de la carptea coctacos y el archivo contactos.js en la carpeta models

2022-09-23 05:00 UTC, lighnio commented
¿Por qué la versión de algunos paquetes cambia?

2022-09-23 05:37 UTC, SFMZ21 requested changes
Rutas y controladores correctos, ¿Por qué hay cambios en las dependencias sequelize y jest? 
¿Por qué se agregó swagger?

2022-09-23 05:38 UTC, DJPORTILLO30 requested changes
Editar destino de pull request ya que va hacia la rama master , necesita ir hacia la rama test-branch! @LuisJuarez17 @larochem20 @Endercarias .

2022-09-24 06:12 UTC, HJOC15 requested changes
Por favor ir agregando comentarios dentro del código.

2022-09-24 18:08 UTC, HJOC15 requested changes
Por favor hacer el cambio de getItems y demás constantes a unas más específicas. Ejemplo: getContactos, createContactos, etc.

2022-10-05 03:20 UTC, HJOC15 approved these changes
¡Todo excelente!

2022-10-05 03:24 UTC, DJPORTILLO30 requested changes
Revisar linea #3 de router/contactos.js el import hace referencia a un archivo que no existe asi como la ortografia de Contacts.

2022-10-05 03:25 UTC, SFMZ21 requested changes
Revisar rutas, todo está escrito como "contacs", revisar el import ya que el archivo se llama "contactos"

2022-10-05 04:26 UTC, DJPORTILLO30 approved these changes
Cambios aprobados!

2022-10-05 04:27 UTC, HJOC15 approved these changes
¡Aprobado!

2022-10-05 04:27 UTC, SFMZ21 approved these changes
Todo ok

2022-10-05 04:29 UTC, merged