Creacion carpetas/ archivos js
DJPORTILLO30/CRM-UMG pull request #14
Opened 2022-09-20 05:19 UTC by larochem20

Creacion de la carpeta campaña y el archivo campaña.js en la carpeta models. Creacion de la carpeta campaña y el archivo campaña.js en la carpeta controllers Creacion de la carpeta campaña y el archivo campaña.js en la carpeta routes

2022-09-23 05:28 UTC, HJOC15 approved these changes
Revisión completada de los controladores y rutas de campañas y no hay ningún error.

Por favor ser más específico a la hora de colocarle nombre al Pull Request.

2022-09-23 05:32 UTC, DJPORTILLO30 commented
Editar destino de pull request ya que va hacia la rama master , necesita ir hacia la rama test-branch! @LuisJuarez17 @larochem20 @Endercarias .

2022-09-24 07:19 UTC, SFMZ21 requested changes
Asignar nombres descriptivos a los controladores y rutas, utilizando Campaign en lugar de item, por ejemplo: getCampaign, createCampaign.

2022-09-26 01:37 UTC, HJOC15 requested changes
Por favor hacer el cambio de la rama Master a la de Test.

2022-10-05 03:36 UTC, HJOC15 requested changes
Revisar la línea de código comentada.

2022-10-05 03:36 UTC, HJOC15 commented on models/campañas/campañas.js
> +module.exports = Contact;
Hicieron mal el copypaste y están exportando contactos, por favor revisar y corregir.

2022-10-05 03:36 UTC, SFMZ21 requested changes
Revisar el modelo, ya que se está exportando "Contact"?

2022-10-05 03:42 UTC, DJPORTILLO30 requested changes
Modifcar el modelo de campaña

2022-10-05 04:29 UTC, HJOC15 approved these changes
Aprobado!

2022-10-05 04:30 UTC, SFMZ21 approved these changes
Todo ok

2022-10-05 04:30 UTC, DJPORTILLO30 approved these changes
Todo okay

2022-10-05 04:31 UTC, merged