Creación de carpetas y archivos para "Permisos"
DJPORTILLO30/CRM-UMG pull request #15
Opened 2022-09-24 03:18 UTC by yesseli

Creación de las carpetas y archivos correspondientes a PERMISOS en las carpetas controllers, models y routes

2022-09-24 03:33 UTC, DJPORTILLO30 requested changes
Por favor revisar el naming del código ya que esta en español y estamos trabajando con nombres en ingles, por ejemplo cambiar insertarPermiso por insertPermission

2022-09-24 04:44 UTC, SFMZ21 approved these changes
Controlador y ruta de permisos correctos.

2022-09-24 04:45 UTC, DJPORTILLO30 approved these changes

2022-09-24 04:45 UTC, DJPORTILLO30 commented
Naming correcto!

2022-09-24 05:53 UTC, HJOC15 commented
Tercera revisión. Controlador y ruta de permisos correcta.

2022-09-24 05:54 UTC, HJOC15 approved these changes

2022-10-05 03:06 UTC, DJPORTILLO30 approved these changes
Todo okay

2022-10-05 03:07 UTC, SFMZ21 approved these changes
Todo bien!

2022-10-05 03:08 UTC, HJOC15 approved these changes
¡Excelente trabajo! Todo está correcto.

2022-10-05 03:09 UTC, merged