Creación de carpetas, rutas y controladores.
DJPORTILLO30/CRM-UMG pull request #17
Opened 2022-09-24 03:56 UTC by JulioF127

Se crearon las carpetas y archivos para las rutas y controladores de los roles para los usuarios.

2022-09-24 06:00 UTC, HJOC15 requested changes
Documentos vacíos.

2022-09-24 07:04 UTC, DJPORTILLO30 requested changes
Faltan archivos de rutas y controladores

2022-09-24 07:10 UTC, SFMZ21 requested changes
Agregar los archivos respectivos.

2022-09-24 17:54 UTC, DJPORTILLO30 requested changes
cambiar el nombre  de los metodos a por ejemplo getRol, insertRol etc.

2022-09-24 18:02 UTC, HJOC15 requested changes
Gracias por comentar el código. Hacer el cambio de mostarRoles a getRoles, por ejemplo, para mantener todo en misma sintonía con los demás. Todo lo demás correcto.

2022-09-24 19:32 UTC, DJPORTILLO30 approved these changes
Todo en orden!

2022-09-26 01:35 UTC, HJOC15 approved these changes
¡Todo está bien!

2022-10-05 03:38 UTC, HJOC15 approved these changes
¡Todo bien! ¡Buen trabajo!

2022-10-05 03:46 UTC, SFMZ21 approved these changes
Todo bien

2022-10-05 03:46 UTC, DJPORTILLO30 approved these changes
Todo okay

2022-10-05 03:48 UTC, merged