Se crearon controladores y rutas.
DJPORTILLO30/CRM-UMG pull request #18
Opened 2022-09-24 05:08 UTC by Hazzel3

Se crearon los 5 controladores para obtener, crear, eliminar, etc. Así mismo se crearon las rutas establecidas.

2022-09-24 06:15 UTC, HJOC15 requested changes
Ir agregando comentarios al código, por favor y revisar la línea de código comentada.

2022-09-24 06:15 UTC, HJOC15 commented on routes/llamadas/llamadas.js
> +const { Router } = require("express");
¿Por qué está esta línea de código?

2022-09-24 06:59 UTC, DJPORTILLO30 requested changes
Corregir error en ruta de llamdas

2022-09-24 06:59 UTC, DJPORTILLO30 commented on routes/llamadas/llamadas.js
> +const { Router } = require("express");
Cambiar esta liena de codigfo ya que hace el llamado a la dependencia de express bajo el nombre de Router, cambiar por const express = require("express"); o similares

2022-09-24 07:07 UTC, SFMZ21 requested changes
Asignar nombres descriptivos a los controladores y rutas, por ejemplo: getCall, createCall... en lugar de item

2022-09-26 01:34 UTC, HJOC15 approved these changes
¡Todos los cambios son correctos!

2022-09-26 02:04 UTC, DJPORTILLO30 reviewed
Todo correcto!

2022-09-26 02:06 UTC, DJPORTILLO30 approved these changes

2022-09-27 04:41 UTC, SFMZ21 approved these changes
Todo bien!

2022-10-05 03:59 UTC, SFMZ21 requested changes
Cambiar el controlador "CallsModel" por "callsModel"

2022-10-05 03:59 UTC, DJPORTILLO30 requested changes
Cambiar CallsModel

2022-10-06 15:41 UTC, HJOC15 approved these changes
¡Cambios arreglados! Muy bien.

2022-10-07 21:36 UTC, DJPORTILLO30 approved these changes
Todo okay

2022-10-14 05:04 UTC, SFMZ21 approved these changes
Todo ok

2022-10-19 21:23 UTC, HJOC15 requested changes
Cambiar el nombre de Llamadas.sql
Quitarle la mayúscula y dejarlo en minúscula: llamadas.sql
Revisar que esto no genere ningún conflicto.

2022-10-28 04:14 UTC, SFMZ21 approved these changes
ok

2022-10-28 04:15 UTC, HJOC15 approved these changes
¡Todo está bien!

2022-10-28 04:16 UTC, merged

2022-10-28 04:16 UTC, DJPORTILLO30 approved these changes
Todo okay

2022-10-28 04:16 UTC, DJPORTILLO30 commented on validators/llamadas.js
> +const validatorCreateBusi = [
El nombre de los metodos corresponde al modulo negocios.