Feature negocios
DJPORTILLO30/CRM-UMG pull request #19
Opened 2022-09-26 02:28 UTC by AngelMCV

Creación de carpetas y archivos en feature-Negocios

2022-09-26 02:31 UTC, HJOC15 approved these changes
¡Todo correcto!

2022-09-26 03:24 UTC, DJPORTILLO30 approved these changes
Todo ok!

2022-09-27 04:50 UTC, SFMZ21 approved these changes
Todo bien!

2022-10-05 04:00 UTC, DJPORTILLO30 requested changes
Cambiar BusisModel

2022-10-05 04:01 UTC, SFMZ21 requested changes
Cambiar el controlador "BusisModel" por "busisModel"

2022-10-06 15:44 UTC, HJOC15 approved these changes
¡Todo bien!

2022-10-07 21:37 UTC, DJPORTILLO30 approved these changes
Cambios realiados correctamente

2022-10-14 05:07 UTC, SFMZ21 approved these changes
Todo ok

2022-10-15 04:08 UTC, DJPORTILLO30 requested changes
Realizar cambios solicitados.

2022-10-15 04:08 UTC, DJPORTILLO30 commented on validators/negocio.js
> +    .notEmpty(), //* .isMongoId(), se le debe de agregar pero cuando se defina la base de datos
Eliminar comentario de ismonoId

2022-10-15 04:08 UTC, DJPORTILLO30 commented on controllers/negocio/negocio.js
> +    console.log(data)
eliminar los console logs.

2022-10-16 21:03 UTC, HJOC15 approved these changes
Todo parece correcto.

2022-10-19 21:24 UTC, HJOC15 approved these changes

2022-10-19 21:25 UTC, HJOC15 requested changes
Cambiar el nombre del documento Negocio.sql
Quitarle la mayúscula y comprobar la integridad al hacer dicho cambio.

2022-10-19 21:41 UTC, HJOC15 commented
Y por favor ir haciendo las pruebas unitarias.

2022-10-21 07:46 UTC, DJPORTILLO30 requested changes
Faltan pruebas unitarias

2022-10-28 04:19 UTC, DJPORTILLO30 approved these changes
Todo okay

2022-10-28 04:20 UTC, HJOC15 approved these changes
¡Todo bien!

2022-10-28 04:20 UTC, merged