Creacion de Carpetas models, routes, controllers
DJPORTILLO30/CRM-UMG pull request #20
Opened 2022-10-01 18:54 UTC by anthony090719

Creacion de carpetas, modelos, rutas y controladores

2022-10-05 03:51 UTC, anthony090719 commented
Actualización controladores, modelos y corrección de rutas

2022-10-05 04:05 UTC, SFMZ21 requested changes
Cambiar el controlador "ProductsModel" por "productsModel", agregar timestamps en el modelo.

2022-10-05 04:05 UTC, DJPORTILLO30 requested changes
Agregar comentarios a las rutas.

2022-10-05 04:08 UTC, HJOC15 requested changes
Revisar la línea de código comentada.

2022-10-05 04:08 UTC, HJOC15 commented on models/Productos/productos.js
> +
Le hizo falta el Timestamps: true al final del modelo. Corregir.

2022-10-07 21:38 UTC, DJPORTILLO30 approved these changes
Cambios correctos!

2022-10-14 05:15 UTC, SFMZ21 requested changes
Cambiar los métodos FindOneAndUpdate por **Update** y el método delete por **destroy** en el controlador.

2022-10-15 13:32 UTC, DJPORTILLO30 requested changes
Realizar cambios correspondientes y agregar:
Query para la tabla.
Pruebas unitarias.

2022-10-15 13:32 UTC, DJPORTILLO30 commented on controllers/Productos/productos.js
> +        const deleteResponse = await productsModel.delete({id});
Cambiar a metodo Sequeelize

2022-10-15 13:32 UTC, DJPORTILLO30 commented on controllers/Productos/productos.js
> +        const products = await productsModel.findOneAndUpdate(id,body);
Cambiar a metodo Sequeelize

2022-10-16 21:06 UTC, HJOC15 requested changes
Eliminar comentarios en inglés del documento productos.sql

2022-10-21 07:45 UTC, DJPORTILLO30 approved these changes
Todo en orden, a la espera de comprobacion de unit tests.

2022-10-22 16:01 UTC, HJOC15 approved these changes
Todo bien.

2022-10-28 04:44 UTC, SFMZ21 approved these changes
Cambios ok

2022-10-28 04:45 UTC, merged