Sprint 4
DJPORTILLO30/CRM-UMG pull request #22
Opened 2022-10-05 04:11 UTC by JulioF127

Creación de rutas, modelos y corrección en controladores.

2022-10-05 04:14 UTC, SFMZ21 requested changes
De dónde estás llamando router?
No estás exportando router....

2022-10-05 04:33 UTC, DJPORTILLO30 requested changes
Cambiar el destino del merge

2022-10-14 05:22 UTC, SFMZ21 requested changes
No ha incorporado los cambios de la rama test-branch

2022-10-19 21:20 UTC, HJOC15 approved these changes
Todo correcto.

2022-10-28 04:18 UTC, DJPORTILLO30 approved these changes
Todo okay

2022-10-28 04:22 UTC, SFMZ21 approved these changes
Todo ok

2022-10-28 04:23 UTC, HJOC15 approved these changes
Curiosos comentario, pero todo nice!

2022-10-28 04:23 UTC, merged