Pruebas unitarias y validators - Feature campañas
DJPORTILLO30/CRM-UMG pull request #27
Opened 2022-10-15 05:29 UTC by LuisJuarez17

Creación de las pruebas unitarias respectivas y validators para campañas. Cambios en las rutas y controladores.

2022-10-15 08:35 UTC, DJPORTILLO30 requested changes
Corregir pruebas unitarias ya que no estan siendo aprobadas.

2022-10-15 08:35 UTC, DJPORTILLO30 commented on test/helper/helperData.js
> +  const testDataCampaign = {
la información no coincide con el modelo.

2022-10-19 21:29 UTC, HJOC15 requested changes
Revisar lo comentado.

2022-10-19 21:29 UTC, HJOC15 commented on models/campañas/campañas.js
> +    nombreCampania: {
Decidir si será campaña o campania, no pueden estar las dos.

2022-10-19 21:36 UTC, HJOC15 commented on models/campañas/campañas.js
> +    nombreCampania: {
Cambiar nombres de español a inglés.

2022-10-28 04:20 UTC, DJPORTILLO30 approved these changes
Todo okay

2022-10-28 04:28 UTC, HJOC15 approved these changes
¡Buenas pruebas unitarias, cracks!

2022-10-28 04:32 UTC, SFMZ21 approved these changes
Todo ok

2022-10-28 04:32 UTC, merged