Creación de validadores y pruebas unitarias
DJPORTILLO30/CRM-UMG pull request #28
Opened 2022-10-15 06:09 UTC by Endercarias

Creación de validadores y pruebas unitarias de contactos, cambios en los controladores y las rutas

2022-10-19 21:32 UTC, HJOC15 requested changes
Eliminar la primera mayúscula de ContactModel en todos lados.
Revisar las líneas de código comentadas.

2022-10-19 21:32 UTC, HJOC15 commented on models/contactos/contactos.js
> +        type: DataTypes.NUMBER,
Si las demás van a estar en español, que teléfono también lo esté.

2022-10-19 21:35 UTC, HJOC15 requested changes

2022-10-19 21:35 UTC, HJOC15 commented on models/contactos/contactos.js
> +        type: DataTypes.NUMBER,
Al hacer revisión de los otros códigos que estén todas en inglés.

2022-10-21 07:47 UTC, DJPORTILLO30 requested changes
A la espera de confirmación de unit test.

2022-10-28 04:21 UTC, DJPORTILLO30 approved these changes
Todo okay

2022-10-28 04:36 UTC, HJOC15 approved these changes
¡Todo bien, gracias las correcciones correspondientes!

2022-10-28 04:41 UTC, SFMZ21 approved these changes
Cambios ok

2022-10-28 04:43 UTC, merged