Feature-Usuarios: Correcciones, validadores y pruebas
DJPORTILLO30/CRM-UMG pull request #29
Opened 2022-10-15 06:28 UTC by yesseli

Se hicieron correcciones en rutas y controladores, se crearon validadores y se realizaron pruebas unitarias

2022-10-15 08:06 UTC, DJPORTILLO30 requested changes
Revisar cambios solicitados.

2022-10-15 08:06 UTC, DJPORTILLO30 commented on controllers/usuarios/usuarios.js
> +        //console.log(body)
eliminar console logs

2022-10-15 08:06 UTC, DJPORTILLO30 commented on utils/handlers/handlePassword.js
> +    //console.log(passwordPlain)
eliminar comentarios

2022-10-15 13:40 UTC, DJPORTILLO30 approved these changes
Todos los cambios en orden!

2022-10-19 21:34 UTC, HJOC15 approved these changes
Todo parece correcto!

2022-10-24 04:36 UTC, SFMZ21 approved these changes
Todo ok

2022-10-24 04:37 UTC, merged